#!/bin/bash

# Função para verificar se o BADVPN está ativo
is_badvpn_active() {
    ps x | grep -w udpvpn | grep -v grep &>/dev/null
}

# Função para exibir o menu
menu_badvpn() {
    clear
    echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
    echo -e "\033[0;34m┃\E[44;1;37m            GERENCIAR BADVPN             \E[0m\033[0;34m┃"
    echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m\n"
    
    if is_badvpn_active; then
        echo -e "\033[1;33mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk '{print $4}' | cut -d: -f2 | xargs)"
    fi

    echo -e "\E[38;5;196m|\E[38;5;33m01\E[38;5;196m|\033[1;37m➜ \033[1;33mATIVAR/DESATIVAR BADVPN (PADRÃO 7300) $([ $(is_badvpn_active) ] && echo "\033[1;32m♦" || echo "\033[1;31m") \033[0m"
    echo -e "\E[38;5;196m|\E[38;5;33m02\E[38;5;196m|\033[1;37m➜ \033[1;33mATIVAR AS PORTAS BADVPN (7100-7900)\033[0m"
    echo -e "\E[38;5;196m|\E[38;5;33m03\E[38;5;196m|\033[1;37m➜ \033[1;33mABRIR PORTA\033[0m"
    echo -e "\E[38;5;196m|\E[38;5;33m00\E[38;5;196m|\033[1;37m➜ \033[1;33mVOLTAR\033[0m"
    echo ""
    echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "
    read resposta

    case "$resposta" in
        1) toggle_badvpn ;;
        2) activate_badvpn_ports ;;
        3) open_badvpn_port ;;
        00) return_to_previous_menu ;;
        *) invalid_option ;;
    esac
}

# Função para iniciar/desativar o BADVPN
toggle_badvpn() {
    if is_badvpn_active; then
        stop_badvpn
    else
        start_badvpn
    fi
}

# Função para iniciar o BADVPN
start_badvpn() {
    clear
    echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
    echo -e "\033[0;34m┃\E[44;1;37m            GERENCIAR BADVPN             \E[0m\033[0;34m┃"
    echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m\n"
    echo -e "\033[1;32mINICIANDO O BADVPN... \033[1;33m"
    install_badvpn_udp
    run_badvpn
    echo -e "\033[1;32mBADVPN ATIVADO COM SUCESSO\033[1;33m"
    sleep 0.5
    menu_badvpn
}

# Função para parar o BADVPN
stop_badvpn() {
    for pid in $(screen -ls | grep ".udpvpn" | awk '{print $1}'); do
        screen -r -S "$pid" -X quit
    done
    sed -i '/udpvpn/d' /etc/autostart
    screen -wipe >/dev/null
    echo -e "\033[1;32mBADVPN DESATIVADO COM SUCESSO!\033[1;33m"
    sleep 0.5
    menu_badvpn
}

# Função para instalar o BADVPN
install_badvpn_udp() {
    cd $HOME
    wget -q https://raw.githubusercontent.com/Lucasoliviveira/vpn/main/I/badvpn-udpgw
    mv -f $HOME/badvpn-udpgw /bin/badvpn-udpgw
    chmod +x /bin/badvpn-udpgw
}

# Função para iniciar o BADVPN
run_badvpn() {
    screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8
    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
}

# Função para ativar as portas BADVPN de 7100 a 7900
activate_badvpn_ports() {
    if is_badvpn_active; then
        echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
        echo -e "\033[0;34m┃\E[44;1;37m            GERENCIAR BADVPN             \E[0m\033[0;34m┃"
        echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m\n"
        echo -e "\033[1;32mINICIANDO TODAS AS PORTAS BADVPN...\033[0m"
        for i in {7100..7900..100}; do
            screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$i --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
        done
        echo -e "\033[1;32mPORTAS BADVPN ATIVADAS...\033[0m"
        sleep 0.5
        menu_badvpn
    fi
}

# Função para abrir uma porta específica do BADVPN
open_badvpn_port() {
    if is_badvpn_active; then
        echo -ne "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m"
        read porta
        if [[ -z "$porta" || ! "$porta" =~ ^[0-9]+$ ]]; then
            echo -e "\033[1;31mPorta inválida!\033[0m"
            sleep 0.5
            menu_badvpn
        fi
        echo -e "\033[1;32mINICIANDO O BADVPN NA PORTA $porta...\033[1;33m"
        screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$porta --max-clients 10000 --max-connections-for-client 8
        echo -e "\033[1;32mPORTA $porta ATIVADA COM SUCESSO\033[0m"
        sleep 0.5
        menu_badvpn
    else
        echo -e "\033[1;31mFUNÇÃO INDISPONÍVEL! ATIVE O BADVPN PRIMEIRO.\033[0m"
        sleep 0.5
        menu_badvpn
    fi
}

# Função para voltar ao menu anterior
return_to_previous_menu() {
    echo -e "\033[1;31mRetornando...\033[0m"
    sleep 1
    # Adicione o código para retornar ao menu anterior aqui
}

# Função para opção inválida
invalid_option() {
    echo -e "\033[1;31mOpção inválida! Tente novamente.\033[0m"
    sleep 1
    menu_badvpn
}

# Chama a função principal do menu
menu_badvpn
