#!/bin/bash

clear
op=$1

# Verifica se o diretório /usr/share/.plus existe
if [[ ! -d /usr/share/.plus ]]; then
    exit 0
fi

# Função para desinstalar o Squid3 e limpar pacotes antigos
fun_sqd01() {
    # Remove o arquivo de fontes de repositório antigo se ele existir
    if [[ -e /etc/apt/sources.list.d/trusty_sources.list ]]; then
        rm /etc/apt/sources.list.d/trusty_sources.list
        if [[ $(grep -wc 'Debian' /etc/issue.net) -ne 0 ]]; then
            apt-key del 3B4FE6ACC0B21F32
        fi
        apt remove squid3=3.3.8-1ubuntu6 squid=3.3.8-1ubuntu6 squid3-common=3.3.8-1ubuntu6 -y
        apt update -y
        apt autoremove -y
    fi
    apt install squid3 -y
}

# Função para configurar o Squid3 com o repositório Trusty
fun_sqd02() {
    # Adiciona repositório Trusty se ele não existir
    if [[ ! -e /etc/apt/sources.list.d/trusty_sources.list ]]; then
        echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe" > /etc/apt/sources.list.d/trusty_sources.list
    fi

    # Se o sistema for Debian, instala dirmngr e adiciona a chave do repositório Ubuntu
    if [[ $(grep -wc 'Debian' /etc/issue.net) -ne 0 ]]; then
        apt install dirmngr -y
        if [[ $(apt-key list 2>/dev/null | grep -c 'Ubuntu') -eq 0 ]]; then
            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
        fi
    fi

    # Atualiza repositórios e instala o Squid3
    apt update -y
    apt install squid3=3.3.8-1ubuntu6 squid=3.3.8-1ubuntu6 squid3-common=3.3.8-1ubuntu6 -y
    wget -qO- https://raw.githubusercontent.com/Lucasoliviveira/vpn/main/I/squid3 > /etc/init.d/squid3
    chmod +x /etc/init.d/squid3
    update-rc.d squid3 defaults
}

# Executa a função com base na opção fornecida
if [[ $op == '1' ]]; then
    fun_sqd02
else
    fun_sqd01
fi
